Repository Leap1b-23-24/Team2-OMAE, pull requests merged in 2024-03, with the labels that each got.

#5 folder1
  front/src/app/page.tsx
Labels: enhancement

#6 folder2
  front/src/app/Signin/page.tsx
Labels: bug

#10 MOOne
  front/public/pinelogo.png
  front/public/search.png
  front/src/Components/Header/Header.tsx
Labels: documentation

#12 7 header zagvar oroh
  front/public/Profile.png
  front/public/heart.png
  front/public/search.png
  front/public/search.svg
  front/public/shop.png
  front/src/Components/Header/Header.tsx
  front/src/app/page.tsx
Labels: documentation

#13 header
  front/src/Components/Header/Header.tsx
Labels: documentation

#14 category2
  front/src/Components/Header/Menu.tsx
Labels: enhancement

#15 signup1
  Auth/Pinecone Logo.png
  front/public/apple.png
  front/public/google.png
  front/public/microsoft.png
  front/public/pinecone.png
  front/public/svg/arrow.svg
  front/public/svg/pinecone.svg
  front/src/Components/Authentication/SignUp.tsx
  front/src/Components/Authentication/Step.tsx
  front/src/Components/Header/Footer.tsx
  front/src/app/Signup/page.tsx
  front/src/app/globals.css
  front/src/app/page.tsx
Labels: enhancement

#24 custom input
  front/src/Components/Authentication/CustomInput.tsx
  front/src/Components/Authentication/SignUp.tsx
  front/src/app/Signup/page.tsx
  front/src/app/page.tsx
  front/tailwind.config.ts
Labels: enhancement

#25 dashboard header
  front/public/Bell.svg
  front/public/Plogo.svg
  front/public/service.svg
  front/src/Components/header.tsx
Labels: enhancement

#26 next btn
  front/src/Components/Authentication/SignUp.tsx
  front/src/Components/Header/Header.tsx
  front/src/Components/NextBtn.tsx
Labels: enhancement

#28 left button
  front/public/left-arrow.svg
  front/src/Components/Leftbutton.tsx
  front/src/app/page.tsx
Labels: enhancement

#29 Dashboardleft
  front/public/svg/4box.svg
  front/public/svg/income.svg
  front/public/svg/list.svg
  front/public/svg/note.svg
  front/public/svg/settings.svg
  front/src/Components/DashboardLeft.tsx
  front/src/app/DashboardLeft/page.tsx
  front/src/app/page.tsx
Labels: documentation

#30 card
  front/package-lock.json
  front/package.json
  front/src/Components/DashboardTotalCard.tsx
  front/src/app/page.tsx
Labels: documentation

#33 M
  front/src/Components/DeliveryInfo.tsx
  front/src/app/page.tsx
Labels: enhancement

#35 dashboard table
  front/public/shoes.svg
  front/src/Components/Table.tsx
  front/src/app/page.tsx
Labels: enhancement
